"""Initial migration

Revision ID: 83aa9e8b9a05
Revises: 
Create Date: 2021-10-24 17:07:28.856653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83aa9e8b9a05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=32), nullable=True),
    sa.Column('units_plural', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('recipe',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('uploaded', sa.DateTime(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('ingredient_in_recipe',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('ingredient_key', sa.Integer(), nullable=False),
    sa.Column('recipe_key', sa.Integer(), nullable=False),
    sa.Column('optional', sa.Boolean(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_key'], ['ingredient.pk'], ),
    sa.ForeignKeyConstraint(['recipe_key'], ['recipe.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredient_in_recipe')
    op.drop_table('recipe')
    op.drop_table('user')
    op.drop_table('ingredient')
    # ### end Alembic commands ###
