version: "3"
services:
  recipe_buddy:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: Recipe-Buddy
    restart: unless-stopped
    ports:
      - 5000:5000
    environment:
      TZ: America/New_York
      MARIADB_HOST: db
      MARIADB_DATABASE: recipebuddy
      MARIADB_USER: recipebuddy
      MARIADB_PASSWORD: recipebuddy
      FLASK_ENV: development
    volumes:
      - ./data/recipe_buddy:/data
      - .:/usr/src
    networks:
      - recipe-buddy-backend-network
    depends_on:
      - db
  db:
    image: mariadb:10.6.4
    restart: always
    environment:
      TZ: America/New_York
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_DATABASE: recipebuddy
      MARIADB_USER: recipebuddy
      MARIADB_PASSWORD: recipebuddy
    volumes:
      - ./data/mariadb:/var/lib/mysql
    networks:
      - recipe-buddy-backend-network

networks:
  recipe-buddy-backend-network:
    driver: bridge
